stages:
    - staging
    - e2e
    - build

build-docker:
  stage: build
  trigger:
    include: build.gitlab-ci.yml
  only:
    - master
  when: manual

deploy-staging:
  image: jonaskello/docker-and-compose:1.12.1-1.8.0
  stage: staging
  script:
    - docker-compose -f docker-compose.yml -f docker-compose.prod.yml build
    - docker-compose -f docker-compose.yml -f docker-compose.prod.yml down
    - docker-compose -f docker-compose.yml -f docker-compose.prod.yml up -d --force-recreate
  variables:
    DOCKER_HOST: "unix:///var/run/docker.sock"

    #e2e-tests:
    #  stage: e2e
    #  services:
    #    - selenium/standalone-chrome
    #  before_script:
    #    - apk update
    #    - apk add curl musl-dev gcc libffi-dev chromium chromium-chromedriver
    #    - export PATH=$PATH:$HOME/bin
    #    - python -m pip install --upgrade pip
    #  script:
    #    - python -m pip install -r ./e2e_tests/requirements.txt
    #    - curl "http://192.168.84.7/" # verify app is running
    #    - python -m e2e_tests.test_login

e2e-tests:
  stage: e2e
  image: python:3.7
  script:
    - python -m pip install -r ./e2e_tests/requirements.txt
    - pytest -vvv --driver Remote --capability browserName chrome --host selenium --port 4444 e2e_tests/test_login.py
  services:
    - name: selenium/standalone-chrome
      alias: selenium
