image: docker:stable

services:
  - docker:dind

stages:
    - e2e
    - staging
    - build

build-docker:
  stage: build
  trigger:
    include: build.gitlab-ci.yml
  only:
    - master
  when: manual

deploy-staging:
  image: jonaskello/docker-and-compose:1.12.1-1.8.0
  stage: staging
  script:
    - docker-compose -f docker-compose.yml -f docker-compose.prod.yml build
    - docker-compose -f docker-compose.yml -f docker-compose.prod.yml down
    - docker-compose -f docker-compose.yml -f docker-compose.prod.yml up -d
  variables:
    DOCKER_HOST: "unix:///var/run/docker.sock"
  when: manual

e2e-tests:
  stage: e2e
  variables:
    RCA_DB_URL: "192.168.84.7"
    RCA_CSV_PATH: "test_results.csv"
    RCA_REPORT_DIR: "reports"
  before_script:
    - apt-get update
    - apt-get install -y curl musl-dev gcc libffi-dev chromium-driver
    - export PATH=/usr/bin/chromedriver:$PATH
    - python -m pip install -U pip setuptools
  script:
    - python -m pip install -r ./e2e_tests/requirements.txt
    - curl "http://192.168.84.7/" # verify app is running
    - mkdir reports
    - python -m unittest discover e2e_tests
  after_script:
    - TraceExplorer
  when: manual
  artifacts:
    when: always
    paths:
    - reports/*.html
    - test_results.csv
    expire_in: 1 week


evaluation:
  stage: e2e
  variables:
    RCA_DB_URL: "192.168.84.7"
    RCA_CSV_PATH: "eval_results.csv"
    RCA_REPORT_DIR: "eval_reports"
  before_script:
    - apt-get update
    - apt-get install -y curl musl-dev gcc libffi-dev chromium-driver
    - export PATH=/usr/bin/chromedriver:$PATH
    - python -m pip install -U pip setuptools
  script:
    - python -m pip install -r ./e2e_tests/requirements.txt
    - curl "http://192.168.84.7/" # verify app is running
    - mkdir eval_reports
    - python -m unittest discover e2e_tests.evaluation_tests
  after_script:
    - TraceExplorer
  when: manual
  artifacts:
    when: always
    paths:
    - eval_reports/*.html
    - eval_results.csv
    expire_in: 1 week


trace_analysis:
  stage: e2e
  image: docker/compose
  services:
  - docker:dind
  variables:
    DOCKER_DRIVER: overlay2
  script:
    - docker-compose -f docker-compose.yml -f docker-compose.prod.yml up -d --build
    - docker exec -i umbrella_db sh -c 'exec mysql -uroot -proot' < ./e2e_tests/testdata.sql
    - docker build -f e2e_tests/Dockerfile -t umbrella_test_runner --build-arg docker_host=172.17.0.1 ./e2e_tests
    - mkdir reports # Verzeichnis für die Auswertungsberichte in HTML: Auf dem Host verfuegbar
    - docker run -d -v $(pwd)/reports:/code/eval_reports --add-host=host.docker:172.17.0.1 --name e2e_runner umbrella_test_runner
    - docker exec -it e2e_runner python -m unittest discover # Testausfuehrung
    - docker exec -it e2e_runner TraceExplorer # Trace-Auswertung
  when: manual
  artifacts:
    when: always
    paths:
    - reports/*.html
    expire_in: 1 week
