stages:
    - e2e
    - staging
    - build

build-docker:
  stage: build
  trigger:
    include: build.gitlab-ci.yml
  only:
    - master
  when: manual

deploy-staging:
  image: jonaskello/docker-and-compose:1.12.1-1.8.0
  stage: staging
  script:
    - docker-compose -f docker-compose.yml -f docker-compose.prod.yml build
    - docker-compose -f docker-compose.yml -f docker-compose.prod.yml down
    - docker-compose -f docker-compose.yml -f docker-compose.prod.yml up -d
  variables:
    DOCKER_HOST: "unix:///var/run/docker.sock"
  when: manual

e2e-tests:
  stage: e2e
  variables:
    RCA_DB_URL: "192.168.84.7"
    RCA_CSV_PATH: "test_results.csv"
    RCA_REPORT_DIR: "reports"
  before_script:
    - apt-get update
    - apt-get install -y curl musl-dev gcc libffi-dev chromium-driver
    - export PATH=/usr/bin/chromedriver:$PATH
    - python -m pip install -U pip setuptools
  script:
    - python -m pip install -r ./e2e_tests/requirements.txt
    - curl "http://192.168.84.7/" # verify app is running
    - mkdir reports
    - python -m e2e_tests.test_login
  after_script:
    - TracingRCA
  artifacts:
    when: always
    paths:
    - reports/
    - test_results.csv
    expire_in: 1 week
