stages:
    - test
    - build

build-all:
  stage: build
  trigger:
    include: build.gitlab-ci.yml

    #e2e-tests:
    #  stage: test
    #  trigger:
    #    include: e2e.gitlab-ci.yml

e2e-tests:
  stage: test
  before_script:
    - apk update
    - apk add curl
  script:
    - curl "http://192.168.84.7/"
