version: "3"
services:
  db:
    expose:
      - 3306

  rabbitmq:
    expose:
      - 5672

  redis:
    expose:
      - 6379

  flower:
    expose:
      - 8888

  minio:
    expose:
      - 9000
      - 9090

  web:
    command: gunicorn web.wsgi:application --bind 0.0.0.0:8000
    expose:
      - 8000
    env_file:
      - ./.env.prod

  frontend:
    command: gunicorn web.wsgi:application --bind 0.0.0.0:8050
    expose:
      - 8050
    env_file:
      - ./.env.prod

  nginx:
    build: ./nginx
    ports:
      - 80:80
    depends_on:
      - web
      - frontend
