version: "3"
services:
  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: umbrella
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    volumes:
      - ./volumes/db/dump.sql:/docker-entrypoint-initdb.d/dump.sql
      - mysql-data:/var/lib/mysql

  rabbitmq:
    image: rabbitmq:latest
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest

  redis:
    image: redis:latest

  flower:
    image: mher/flower
    environment: 
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672//
      - FLOWER_PORT=8888
    depends_on: 
      - rabbitmq
      - redis

  minio:
    image: minio/minio
    command: server /export --console-address ":9090"
    volumes:
      - ./volumes/minio:/export
    environment:
      - MINIO_ACCESS_KEY=access-key
      - MINIO_SECRET_KEY=secret-key

  web:
    image: web
    hostname: web
    build: 
        context: .
        dockerfile: ./web/Dockerfile
    volumes:
      - ./web/:/code/
    depends_on:
      - db
    environment:
      - DJANGO_ALLOWED_HOSTS=web localhost 192.168.84.7
      - BROKER_URL=amqp://guest:guest@rabbitmq//
      - REDIS_URL=redis://redis
      - SQL_HOST=db
      - EXTERNAL_API_URL=http://192.168.84.7:8000

  frontend:
    image: web
    build: 
        context: .
        dockerfile: ./web/Dockerfile
    volumes:
      - ./web/:/code/
    links:
      - web:web
    depends_on:
      - db
    environment:
      - DJANGO_ALLOWED_HOSTS=web localhost 192.168.84.7
      - BROKER_URL=amqp://guest:guest@rabbitmq//
      - REDIS_URL=redis://redis
      - SQL_HOST=db
      - EXTERNAL_API_URL=http://192.168.84.7:8000

  scripts:
    image: scripts_worker
    build:
      context: .
      dockerfile: ./scripts/Dockerfile
    deploy:
      replicas: 1
    environment:
      - BROKER_URL=amqp://guest:guest@rabbitmq//
      - REDIS_URL=redis://redis
      - API_URL=http://web:8000/
    extra_hosts:
    - "host.docker.internal:host-gateway"
      
  hello:
    image: hello_worker
    build:
        context: .
        dockerfile: ./hello/Dockerfile
    deploy:
        replicas: 1
    environment:
      - BROKER_URL=amqp://guest:guest@rabbitmq//
      - REDIS_URL=redis://redis

  storage:
    image: storage_worker
    build:
      context: .
      dockerfile: ./storage/Dockerfile
    deploy:
      replicas: 1
    environment:
      - BROKER_URL=amqp://guest:guest@rabbitmq//
      - REDIS_URL=redis://redis
      - MINIO_ACCESS_KEY=access-key
      - MINIO_SECRET_KEY=secret-key
      - MINIO_ENDPOINT=minio:9000
      - MINIO_SECURE=0

  pinger:
    image: pinger_worker
    build:
        context: .
        dockerfile: ./pinger/Dockerfile
    deploy:
        replicas: 1
    environment:
      - BROKER_URL=amqp://guest:guest@rabbitmq//
      - REDIS_URL=redis://redis  

volumes:
  mysql-data:
