version: "2"
services:
  db:
    expose:
      - 3306

  rabbitmq:
    expose:
      - 5672

  redis:
    expose:
      - 6379

  flower:
    expose:
      - 8888

  minio:
    expose:
      - 9000
      - 9090

  api:
    command: daphne -b 0.0.0.0 -p 8000 web.asgi:application
    expose:
      - 8000
    env_file:
      - ./.env.prod
    environment:  
      - EXTERNAL_API_URL=http://192.168.84.7:80
      - DJANGO_SETTINGS_MODULE=web.settings

  frontend:
    command: daphne -b 0.0.0.0 -p 8050 web.asgi:application
    expose:
      - 8050
    env_file:
      - ./.env.prod
    environment:  
      - EXTERNAL_API_URL=http://192.168.84.7:80
      - DJANGO_SETTINGS_MODULE=web.settings

  nginx:
    build:
        context: .
        dockerfile: ./nginx/Dockerfile
    ports:
      - 80:80
    depends_on:
      - api
      - frontend
