version: "3"
services:
  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: umbrella
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    volumes:
      - ./volumes/db:/var/lib/mysql
    ports:
      - "3302:3306"

  rabbitmq:
    image: rabbitmq:latest
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  flower:
    image: mher/flower
    environment: 
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672//
      - FLOWER_PORT=8888
    ports: 
      - 8888:8888
    depends_on: 
      - rabbitmq
      - redis

  minio:
    image: minio/minio
    command: server /export --console-address ":9090"
    volumes:
      - ./volumes/minio:/export
    ports:
      - 9000:9000
      - 9090:9090
    environment:
      - MINIO_ACCESS_KEY=access-key
      - MINIO_SECRET_KEY=secret-key

  web:
    image: web
    build: 
        context: .
        dockerfile: ./web/Dockerfile
    command: gunicorn web.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./web/:/code/
    expose:
      - 8000
    depends_on:
      - db
    env_file:
      - ./.env.prod
    environment:
      - DJANGO_ALLOWED_HOSTS=web localhost
      - BROKER_URL=amqp://guest:guest@rabbitmq//
      - REDIS_URL=redis://redis
      - SQL_HOST=db

  frontend:
    image: web
    build: 
        context: .
        dockerfile: ./web/Dockerfile
    command: gunicorn web.wsgi:application --bind 0.0.0.0:8050
    volumes:
      - ./web/:/code/
    expose:
      - 8050
    depends_on:
      - db
    env_file:
      - ./.env.prod
    environment:
      - DJANGO_ALLOWED_HOSTS=web localhost
      - BROKER_URL=amqp://guest:guest@rabbitmq//
      - REDIS_URL=redis://redis
      - SQL_HOST=db

  nginx:
    build: ./nginx
    ports:
      - 80:80
    depends_on:
      - web
      - frontend

  scripts:
    image: scripts_worker
    build:
      context: .
      dockerfile: ./scripts/Dockerfile
    deploy:
      replicas: 1
    environment:
      - BROKER_URL=amqp://guest:guest@rabbitmq//
      - REDIS_URL=redis://redis
      - API_URL=http://web:8000/
      
  hello:
    image: hello_worker
    build:
        context: .
        dockerfile: ./hello/Dockerfile
    deploy:
        replicas: 1
    environment:
      - BROKER_URL=amqp://guest:guest@rabbitmq//
      - REDIS_URL=redis://redis

  storage:
    image: storage_worker
    build:
      context: .
      dockerfile: ./storage/Dockerfile
    deploy:
      replicas: 1
    environment:
      - BROKER_URL=amqp://guest:guest@rabbitmq//
      - REDIS_URL=redis://redis
      - MINIO_ACCESS_KEY=access-key
      - MINIO_SECRET_KEY=secret-key
      - MINIO_ENDPOINT=minio:9000
      - MINIO_SECURE=0

  ssh-server:
    image: linuxserver/openssh-server
    container_name: ssh-server
    hostname: ssh-server
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - PUBLIC_KEY_FILE=./ssh_client_rsa.pub
      - PASSWORD_ACCESS=true
      - USER_PASSWORD=password
      - USER_NAME=ssh.user
    ports:
      - 2222:2222
    restart: unless-stopped

  ssh-python-server:
    image: eugenes1/python-sshd
    container_name: ssh-python-server
    hostname: ssh-python-server   
    deploy:
        replicas: 1  
    ports:
      - 3333:0022