# Generated by Django 3.2.8 on 2021-10-22 14:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('content', models.TextField(blank=True)),
                ('type', models.CharField(choices=[('sh', 'Bash'), ('py', 'Python')], max_length=3)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('os', models.CharField(choices=[('windows', 'Windows'), ('linux', 'Linux')], help_text='Operating System', max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Peer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('ssh_port', models.IntegerField(default=22)),
                ('hostname', models.CharField(max_length=50, null=True, unique=True)),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('private_key', models.TextField(null=True)),
                ('passphrase', models.CharField(blank=True, default='', max_length=20)),
                ('os', models.CharField(choices=[('windows', 'Windows'), ('linux', 'Linux')], help_text='Operating System', max_length=7)),
            ],
        ),
    ]
