# Generated by Django 3.2.8 on 2021-10-23 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peer',
            name='hostname',
            field=models.CharField(default='exit', max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='peer',
            name='ip_address',
            field=models.GenericIPAddressField(null=True),
        ),
    ]
